/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package org.caferrerb.drawer.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PAR_ABIERTO = 5;
  /** RegularExpression Id. */
  int PAR_CERRADO = 6;
  /** RegularExpression Id. */
  int ASIGNACION = 7;
  /** RegularExpression Id. */
  int COMA = 8;
  /** RegularExpression Id. */
  int NUMERO = 9;
  /** RegularExpression Id. */
  int CIRCULO = 10;
  /** RegularExpression Id. */
  int RECTANGULO = 11;
  /** RegularExpression Id. */
  int PUNTO = 12;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\",\"",
    "<NUMERO>",
    "\"circulo\"",
    "\"rectangulo\"",
    "\"punto\"",
    "<IDENTIFICADOR>",
  };

}
